database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: sa
  url: jdbc:postgresql://db:5432/mydb

databaseExtra:
  name: mydb
  dockerImage: postgres
  initScript: "classpath:database/db-init.sql"

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  # Logger-specific levels.
  loggers:
    io.baris.petclinic: DEBUG
    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG
