version: "3.9"
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sa"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
  petclinic:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
volumes:
  db:
    driver: local

