version: '3.9'

services:
  app:
    build: .
    environment:
      # required
      NEW_RELIC_LICENSE_KEY: $NEW_RELIC_LICENSE_KEY
      # optional
      NEW_RELIC_HOST: ${NEW_RELIC_HOST:-}
    ports:
      - "4080:4080"
      - "4081:4081"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sa"
