resourcePackages:
  - io.baris.petclinic
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0'
    title: Pet Clinic
    description: Pet Clinic
    termsOfService: http://baris.io/terms/
    contact:
      email: basaran.baris@gmail.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
